export enum DisputeType {
  RENT_PAYMENT = 'RENT_PAYMENT',
  SECURITY_DEPOSIT = 'SECURITY_DEPOSIT',
  PROPERTY_DAMAGE = 'PROPERTY_DAMAGE',
  MAINTENANCE = 'MAINTENANCE',
  TERMINATION = 'TERMINATION',
  OTHER = 'OTHER',
}
